### ISSUE TITLE
Duplicate definition error for 'read','write','init','modify' methods within the type RegCore

### ISSUE THREAD

**Issue by AthiraRamakrishna** [Infineon/svd2pac#3]
**Description**:
RegCore type has Trait bounds <T: RegSpec<DataType = u32>, A: Access, const ADDR: u16> and <T: RegSpec<DataType = u64>, A: Access, const ADDR: u16> to conditionally implement the respective read write methods for 32 and 64 bits, but compiler throws duplicate definition error.

**Steps to Reproduce:**
        1. Checkout svd2pac
	2. Generate the svd2pac executable --> cargo build
	3. Generate a pac for simple_csfr.svd -->   .\target\debug\svd2pac.exe .\test_svd\simple_csfr.svd --target=aurix output  
	4. Set the default toolchain to tricore --> rustup default tricore-htc-none-v0.2.0
	5. Compiler the newly generated pac in the output folder by setting the target tc18 --> cargo build --target tc18-htc-none      

**Build/Commit:**

Used the master branch with last commit revision: 40f12e56

**Target:**

tc18

**Host OS and Version:**

Windows

**Compiler:**

rustc 1.72.0-dev (HighTec Rust Aurix compiler version 0.2.0)

**Comment by andreasWallnerIFX** [comment]
Thanks for the report!
From the description this does not sound like it should be a tricore specific issue, does it also occur with other compilers?

**Comment by AthiraRamakrishna** [comment]
No it doesnt, RegCore type is applicable only to core special function registers(csfr) of tricore. Observed only when compiled for tc18 target.
