### ISSUE TITLE
Add hints (#[diagnostic::on_unimplemented]) to required interface required by `tracing` feature 

### ISSUE THREAD

**Issue by pellico** [Infineon/svd2pac#34]
To use `tracing` is required to implement a trait to log register access.
It would be easier to use if there is a informative message to explain what to implement in case of of missing implementation

**Describe the solution you'd like**

Use  [diagnostic attribute](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-diagnosticon_unimplemented-attribute)

**Comment by andreasWallnerIFX** [comment]
The attribute doesn't really apply to our use case: we don't have a trait that we could mark since we add read/write/read-modify-write callback separately.
